=== Microsoft/wineryjs/schema/object-type-config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://winery.napajs.org/object-type-config",
  "type": "array",
  "title": "Type config schema in Napa.",
  "description": "Type config is a sub config file under app config in Napa.",
  "name": "/",
  "items": {
    "id": "http://winery.napajs.org/object-type-config/item",
    "type": "object",
    "title": "Type definition schema.",
    "description": "Type definition describes type name and where the constructor locates.",
    "name": "item",
    "properties": {
      "typeName": {
        "id": "http://winery.napajs.org/object-type-config/item/typeName",
        "type": "string",
        "title": "Type schema.",
        "description": "Type name, case-sensitive.",
        "name": "typeName"
      },
      "override": {
        "id": "http://winery.napajs.org/object-type-config/item/override",
        "type": "boolean",
        "title": "Override schema.",
        "description": "If this type will override the same type name declared before this definition..",
        "name": "override",
        "default": false
      },
      "description": {
        "id": "http://winery.napajs.org/object-type-config/item/description",
        "type": "string",
        "title": "Description schema.",
        "description": "Description of the type.",
        "name": "description"
      },
      "moduleName": {
        "id": "http://winery.napajs.org/object-type-config/item/moduleName",
        "type": "string",
        "title": "Module name schema.",
        "description": "Module name of the constructor.",
        "name": "moduleName"
      },
      "functionName": {
        "id": "http://winery.napajs.org/object-type-config/item/functionName",
        "type": "string",
        "title": "Function name schema.",
        "description": "Function name as constructor.",
        "name": "functionName"
      },
      "schema": {
        "id": "http://winery.napajs.org/object-type-config/item/schema",
        "type": "string",
        "title": "JSON Schema for value element.",
        "description": "JSON schema for value element.",
        "name": "schema"
      },
      "exampleObjects": {
        "id": "http://winery.napajs.org/provider-config/item/exampleObjects",
        "type": "array",
        "title": "Example objects schema.",
        "description": "Example objects for current type.",
        "name": "exampleObjects",
        "items": {}
      }
    },
    "additionalProperties": false,
    "required": [
      "typeName",
      "description",
      "moduleName",
      "functionName",
      "exampleObjects"
    ]
  }
}

=== Microsoft/wineryjs/test/test-app/object-types.json
[
    {
        "typeName": "TypeA",
        "description": "Test type A",
        "moduleName": "./test-app",
        "functionName": "types.createA",
        "exampleObjects": [
            {
                "_type": "TypeA",
                "value": 1
            }
        ]
    },
    {
        "typeName": "TypeB",
        "description": "Test type B",
        "moduleName": "./test-app",
        "functionName": "types.createB_app",
        "exampleObjects": [
            {
                "_type": "TypeB",
                "value": "abc"
            }
        ]
    },
    {
        "typeName": "TypeC",
        "description": "Test type C",
        "moduleName": "./test-app",
        "functionName": "types.createC_app",
        "exampleObjects": [
            {
                "_type": "TypeC",
                "value": "abc"
            }
        ]
    }
]
